### ISSUE TITLE
[Feature Request] Enter to submit

### ISSUE THREAD

**Issue by stnor** [powmedia/backbone.bootstrap-modal#21]
When enter is pressed I think "ok" is a resonable default.

I added the following to the events:

```
  'keypress': function(event) {
     if (event.which == 13) {
       event.preventDefault();
       this.trigger('ok');
         if (this.options.content && this.options.content.trigger) {
           this.options.content.trigger('ok', this);
         }

         if (this.options.okCloses) {
           this.close();
         }
       }
    }
```

The above does only seem to work with forms/inputs though...
Perhaps it's something you'd want to add to the offical version?

/Stefan

**Comment by kersten** [comment]
I think the better option would be to make this optional, because sometime you don't want to get the modal closed on enter keypress. I see if I could get this done later today.
