### ISSUE TITLE
Allow the option to focus a text input

### ISSUE THREAD

**Issue by mb-dev** [powmedia/backbone.bootstrap-modal#29]
Currently there is only an option to focus on buttonOk. It would be nice to have the option to focus an arbitrary field by class.

view = new Backbone.BootstrapModal({ content: $('.formclass').html(), focus: 'field_class' }).open();

**Comment by powmedia** [comment]
That's probably outside the scope of this library - you could either use Backbone.Form which makes it easy to to this or do something like the following:

``` js
var content = new Backbone.View(...);

var modal = new Backbone.BootsrapModal({ content: content });
modal.on('show', function() {
  content.$('.field').focus();
});
modal.open();
```

**Comment by powmedia** [comment]
Having said that, if you want to submit a pull request where it accepts a general jQuery selector as the `focus` option I would consider integrating that.
