### ISSUE TITLE
shown event not working

### ISSUE THREAD

**Issue by techcto** [powmedia/backbone.bootstrap-modal#44]
I hope this is user error, but I am unable to get the shown event working.  I have tried several combinations.

modal = new Backbone.BootstrapModal({ content: view, title: title, animate: true }).open();

```
                        modal.bind("shown", function(){
                            alert("hello");
                        });
```

Is this a possible conflict with bootstrap?

**Comment by ihortymoshenko** [comment]
@solodev, it can be related to the issue https://github.com/powmedia/backbone.bootstrap-modal/pull/45.
