### ISSUE TITLE
return data

### ISSUE THREAD

**Issue by hlarcher** [powmedia/backbone.bootstrap-modal#72]
Great job with this plugin, worked out of the box but now I'm having trouble figuring out how to get data from the content on Ok click, for example lets say I have an input field and write something in it, how do I get that data out when I click ok?

Thanks in advance

**Comment by powmedia** [comment]
That depends on how you implement the view that you inject into the modal, e.g.:

```
var myView = new Backbone.View(...);

var modal = new Backbone.BootstrapModal({ content: myView }).open();

modal.on('ok', function() {
  var val = myView.$('input').val();
});
```

**Comment by hlarcher** [comment]
Makes sense, thanks a lot
